/**
 * Regenerates config/bot/zone-countries.tsv (spec 007 research R9) from tzdata's zone1970.tab and
 * zone.tab (public domain). zone.tab adds zones that zone1970.tab folds into others (Europe/Oslo),
 * which browsers still report. Download https://data.iana.org/time-zones/tzdata-latest.tar.gz by
 * hand and pass the extracted files and the tzdata version:
 *
 *   bun run scripts/zone-countries.ts <zone1970.tab> <zone.tab> <tzdata version>
 */
import { join } from "node:path";

const [zone1970, zoneTab, version] = Bun.argv.slice(2);
if (!zone1970 || !zoneTab || !version) {
  console.error("usage: bun run scripts/zone-countries.ts <zone1970.tab> <zone.tab> <tzdata version>");
  process.exit(2);
}

const zones = new Map<string, Set<string>>();
const lines = [...(await Bun.file(zone1970).text()).split("\n"), ...(await Bun.file(zoneTab).text()).split("\n")];
for (const line of lines) {
  if (line.startsWith("#") || line.trim() === "") continue;
  const [codes, , zone] = line.split("\t");
  if (!codes || !zone || !/^[A-Z]{2}(,[A-Z]{2})*$/.test(codes)) throw new Error(`unexpected line: ${line}`);
  const set = zones.get(zone) ?? new Set<string>();
  for (const code of codes.split(",")) set.add(code);
  zones.set(zone, set);
}
for (const zone of ["UTC", "Etc/UTC"]) zones.set(zone, new Set());

const rows = [...zones.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([zone, codes]) => `${zone}\t${[...codes].sort().join(",")}`);
const header = [
  `# IANA time zone -> ISO 3166 country codes, from tzdata ${version} zone1970.tab and zone.tab (public domain).`,
  "# Generated by scripts/zone-countries.ts; do not edit by hand. UTC zones belong to no country.",
];
const out = join(import.meta.dir, "..", "config", "bot", "zone-countries.tsv");
await Bun.write(out, `${[...header, ...rows].join("\n")}\n`);
console.log(`${rows.length} zones written to ${out}`);
